// amphi-assistant/agents/amphi-etl/examples/integration/react-chat-widget.jsx
/**
 * React 对话组件示例
 * 可嵌入第三方应用的聊天窗口
 */

import React, { useState, useRef, useEffect } from 'react';

// 样式（可使用 CSS-in-JS 或单独 CSS 文件）
const styles = {
  chatContainer: {
    width: '100%',
    maxWidth: '600px',
    height: '700px',
    border: '1px solid #e0e0e0',
    borderRadius: '12px',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#fff',
    boxShadow: '0 4px 20px rgba(0,0,0,0.1)',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    padding: '16px 20px',
    borderBottom: '1px solid #e0e0e0',
    backgroundColor: '#f8f9fa',
    borderRadius: '12px 12px 0 0',
  },
  title: {
    margin: 0,
    fontSize: '18px',
    fontWeight: 600,
    color: '#1a1a1a',
  },
  subtitle: {
    margin: '4px 0 0 0',
    fontSize: '13px',
    color: '#666',
  },
  messagesContainer: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  message: {
    maxWidth: '85%',
    padding: '12px 16px',
    borderRadius: '12px',
    fontSize: '14px',
    lineHeight: 1.6,
    wordWrap: 'break-word',
  },
  userMessage: {
    alignSelf: 'flex-end',
    backgroundColor: '#007bff',
    color: '#fff',
    borderBottomRightRadius: '4px',
  },
  botMessage: {
    alignSelf: 'flex-start',
    backgroundColor: '#f1f3f4',
    color: '#1a1a1a',
    borderBottomLeftRadius: '4px',
  },
  inputContainer: {
    padding: '16px 20px',
    borderTop: '1px solid #e0e0e0',
    display: 'flex',
    gap: '12px',
  },
  input: {
    flex: 1,
    padding: '12px 16px',
    border: '1px solid #ddd',
    borderRadius: '24px',
    fontSize: '14px',
    outline: 'none',
    transition: 'border-color 0.2s',
  },
  sendButton: {
    padding: '12px 24px',
    backgroundColor: '#007bff',
    color: '#fff',
    border: 'none',
    borderRadius: '24px',
    fontSize: '14px',
    fontWeight: 500,
    cursor: 'pointer',
    transition: 'background-color 0.2s',
  },
  sendButtonDisabled: {
    backgroundColor: '#ccc',
    cursor: 'not-allowed',
  },
  status: {
    padding: '8px 16px',
    fontSize: '12px',
    color: '#666',
    textAlign: 'center',
    backgroundColor: '#f8f9fa',
  },
  pipelineBadge: {
    display: 'inline-block',
    padding: '4px 8px',
    backgroundColor: '#28a745',
    color: '#fff',
    borderRadius: '4px',
    fontSize: '12px',
    marginTop: '8px',
  },
  phaseIndicator: {
    padding: '4px 12px',
    borderRadius: '12px',
    fontSize: '11px',
    fontWeight: 500,
    textTransform: 'uppercase',
  },
};

// 阶段颜色映射
const phaseColors = {
  INITIAL: '#6c757d',
  PROPOSING: '#007bff',
  COLLECTING: '#ffc107',
  CONFIRMING: '#17a2b8',
  COMPLETED: '#28a745',
};

// 阶段中文映射
const phaseLabels = {
  INITIAL: '初始',
  PROPOSING: '方案',
  COLLECTING: '收集',
  CONFIRMING: '确认',
  COMPLETED: '完成',
};

function ETLChatWidget({ 
  apiBaseUrl = '/api/chat',
  userId = 'anonymous',
  title = '🤖 ETL 智能助手',
  subtitle = '告诉我你的数据处理需求'
}) {
  const [messages, setMessages] = useState([]);
  const [inputValue, setInputValue] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [sessionId, setSessionId] = useState(null);
  const [phase, setPhase] = useState('INITIAL');
  const [isComplete, setIsComplete] = useState(false);
  const messagesEndRef = useRef(null);

  // 初始化会话
  useEffect(() => {
    createSession();
  }, []);

  // 自动滚动到底部
  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const createSession = async () => {
    try {
      const response = await fetch(`${apiBaseUrl}/session`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ userId }),
      });
      
      const data = await response.json();
      if (data.success) {
        setSessionId(data.sessionId);
        // 添加欢迎消息
        setMessages([{
          role: 'assistant',
          content: '你好！我是 ETL 智能助手。请描述你的数据处理需求，例如：\n• "把CSV文件导入MySQL数据库"\n• "从PostgreSQL导出数据到CSV"',
          timestamp: Date.now(),
        }]);
      }
    } catch (error) {
      console.error('创建会话失败:', error);
      setMessages([{
        role: 'assistant',
        content: '抱歉，连接服务失败，请稍后重试。',
        timestamp: Date.now(),
      }]);
    }
  };

  const sendMessage = async () => {
    if (!inputValue.trim() || !sessionId || isLoading) return;

    const userMessage = inputValue.trim();
    setInputValue('');
    setIsLoading(true);

    // 添加用户消息
    setMessages(prev => [...prev, {
      role: 'user',
      content: userMessage,
      timestamp: Date.now(),
    }]);

    try {
      const response = await fetch(`${apiBaseUrl}/message`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          sessionId,
          message: userMessage,
          userId,
        }),
      });

      const data = await response.json();
      
      if (data.success) {
        const { response: botResponse, phase: newPhase, isComplete: complete, pipelineFile } = data.data;
        
        setPhase(newPhase);
        setIsComplete(complete);
        
        setMessages(prev => [...prev, {
          role: 'assistant',
          content: botResponse,
          timestamp: Date.now(),
          pipelineFile,
          phase: newPhase,
        }]);
      } else {
        throw new Error(data.error);
      }
    } catch (error) {
      setMessages(prev => [...prev, {
        role: 'assistant',
        content: '抱歉，处理消息时出现错误，请重试。',
        timestamp: Date.now(),
        isError: true,
      }]);
    } finally {
      setIsLoading(false);
    }
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      sendMessage();
    }
  };

  // 格式化消息内容（支持换行）
  const formatMessage = (content) => {
    return content.split('\n').map((line, i) => (
      <span key={i}>
        {line}
        {i < content.split('\n').length - 1 && <br />}
      </span>
    ));
  };

  return (
    <div style={styles.chatContainer}>
      {/* 头部 */}
      <div style={styles.header}>
        <h3 style={styles.title}>{title}</h3>
        <p style={styles.subtitle}>{subtitle}</p>
        {sessionId && (
          <div style={{ marginTop: '8px', display: 'flex', alignItems: 'center', gap: '8px' }}>
            <span style={{ fontSize: '11px', color: '#999' }}>
              会话: {sessionId.slice(0, 8)}...
            </span>
            <span style={{
              ...styles.phaseIndicator,
              backgroundColor: phaseColors[phase] + '20',
              color: phaseColors[phase],
            }}>
              {phaseLabels[phase]}
            </span>
          </div>
        )}
      </div>

      {/* 状态栏 */}
      {isComplete && (
        <div style={{ ...styles.status, backgroundColor: '#d4edda', color: '#155724' }}>
          ✅ Pipeline 已生成完成
        </div>
      )}

      {/* 消息列表 */}
      <div style={styles.messagesContainer}>
        {messages.map((msg, index) => (
          <div
            key={index}
            style={{
              ...styles.message,
              ...(msg.role === 'user' ? styles.userMessage : styles.botMessage),
              ...(msg.isError ? { backgroundColor: '#f8d7da', color: '#721c24' } : {}),
            }}
          >
            {formatMessage(msg.content)}
            {msg.pipelineFile && (
              <div style={styles.pipelineBadge}>
                📁 Pipeline 已保存
              </div>
            )}
          </div>
        ))}
        {isLoading && (
          <div style={{ ...styles.message, ...styles.botMessage }}>
            <span>思考中</span>
            <span className="typing-indicator">...</span>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      {/* 输入区域 */}
      <div style={styles.inputContainer}>
        <input
          type="text"
          value={inputValue}
          onChange={(e) => setInputValue(e.target.value)}
          onKeyPress={handleKeyPress}
          placeholder={isComplete ? '会话已完成，可以开始新的对话' : '输入你的需求...'}
          style={styles.input}
          disabled={isLoading || isComplete}
        />
        <button
          onClick={sendMessage}
          disabled={isLoading || !inputValue.trim() || isComplete}
          style={{
            ...styles.sendButton,
            ...(isLoading || !inputValue.trim() || isComplete ? styles.sendButtonDisabled : {}),
          }}
        >
          {isLoading ? '发送中...' : '发送'}
        </button>
      </div>
    </div>
  );
}

export default ETLChatWidget;

// amphi-assistant/agents/amphi-etl/examples/integration/vue-chat-widget.vue
<template>
  <!-- Vue 3 对话组件示例 -->
  <div class="etl-chat-widget">
    <!-- 头部 -->
    <div class="chat-header">
      <h3 class="title">{{ title }}</h3>
      <p class="subtitle">{{ subtitle }}</p>
      <div v-if="sessionId" class="session-info">
        <span class="session-id">会话: {{ sessionId.slice(0, 8) }}...</span>
        <span class="phase-badge" :style="phaseStyle">{{ phaseLabel }}</span>
      </div>
    </div>

    <!-- 完成状态 -->
    <div v-if="isComplete" class="status-bar success">
      ✅ Pipeline 已生成完成
    </div>

    <!-- 消息列表 -->
    <div class="messages-container" ref="messagesContainer">
      <div
        v-for="(msg, index) in messages"
        :key="index"
        :class="['message', msg.role, { error: msg.isError }]"
      >
        <div class="message-content" v-html="formatMessage(msg.content)"></div>
        <div v-if="msg.pipelineFile" class="pipeline-badge">
          📁 Pipeline 已保存
        </div>
      </div>
      
      <!-- 加载中 -->
      <div v-if="isLoading" class="message bot">
        <span>思考中...</span>
      </div>
    </div>

    <!-- 输入区域 -->
    <div class="input-container">
      <input
        v-model="inputValue"
        @keyup.enter="sendMessage"
        :placeholder="isComplete ? '会话已完成' : '输入你的需求...'
        :disabled="isLoading || isComplete"
        class="message-input"
      />
      <button
        @click="sendMessage"
        :disabled="isLoading || !inputValue.trim() || isComplete"
        class="send-button"
      >
        {{ isLoading ? '发送中...' : '发送' }}
      </button>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted, nextTick } from 'vue';

const props = defineProps({
  apiBaseUrl: {
    type: String,
    default: '/api/chat'
  },
  userId: {
    type: String,
    default: 'anonymous'
  },
  title: {
    type: String,
    default: '🤖 ETL 智能助手'
  },
  subtitle: {
    type: String,
    default: '告诉我你的数据处理需求'
  }
});

// 状态
const messages = ref([]);
const inputValue = ref('');
const isLoading = ref(false);
const sessionId = ref(null);
const phase = ref('INITIAL');
const isComplete = ref(false);
const messagesContainer = ref(null);

// 阶段配置
const phaseConfig = {
  INITIAL: { label: '初始', color: '#6c757d' },
  PROPOSING: { label: '方案', color: '#007bff' },
  COLLECTING: { label: '收集', color: '#ffc107' },
  CONFIRMING: { label: '确认', color: '#17a2b8' },
  COMPLETED: { label: '完成', color: '#28a745' },
};

const phaseLabel = computed(() => phaseConfig[phase.value]?.label || '未知');
const phaseStyle = computed(() => ({
  backgroundColor: phaseConfig[phase.value]?.color + '20',
  color: phaseConfig[phase.value]?.color,
}));

// 初始化
onMounted(() => {
  createSession();
});

// 创建会话
const createSession = async () => {
  try {
    const response = await fetch(`${props.apiBaseUrl}/session`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ userId: props.userId }),
    });
    
    const data = await response.json();
    if (data.success) {
      sessionId.value = data.sessionId;
      messages.value.push({
        role: 'assistant',
        content: '你好！我是 ETL 智能助手。请描述你的数据处理需求，例如：\n• "把CSV文件导入MySQL数据库"\n• "从PostgreSQL导出数据到CSV"',
        timestamp: Date.now(),
      });
    }
  } catch (error) {
    console.error('创建会话失败:', error);
    messages.value.push({
      role: 'assistant',
      content: '抱歉，连接服务失败，请稍后重试。',
      timestamp: Date.now(),
    });
  }
};

// 发送消息
const sendMessage = async () => {
  const userMessage = inputValue.value.trim();
  if (!userMessage || !sessionId.value || isLoading.value) return;

  inputValue.value = '';
  isLoading.value = true;

  // 添加用户消息
  messages.value.push({
    role: 'user',
    content: userMessage,
    timestamp: Date.now(),
  });

  scrollToBottom();

  try {
    const response = await fetch(`${props.apiBaseUrl}/message`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        sessionId: sessionId.value,
        message: userMessage,
        userId: props.userId,
      }),
    });

    const data = await response.json();
    
    if (data.success) {
      const { response: botResponse, phase: newPhase, isComplete: complete, pipelineFile } = data.data;
      
      phase.value = newPhase;
      isComplete.value = complete;
      
      messages.value.push({
        role: 'assistant',
        content: botResponse,
        timestamp: Date.now(),
        pipelineFile,
      });
    } else {
      throw new Error(data.error);
    }
  } catch (error) {
    messages.value.push({
      role: 'assistant',
      content: '抱歉，处理消息时出现错误，请重试。',
      timestamp: Date.now(),
      isError: true,
    });
  } finally {
    isLoading.value = false;
    scrollToBottom();
  }
};

// 滚动到底部
const scrollToBottom = () => {
  nextTick(() => {
    if (messagesContainer.value) {
      messagesContainer.value.scrollTop = messagesContainer.value.scrollHeight;
    }
  });
};

// 格式化消息
const formatMessage = (content) => {
  return content.replace(/\n/g, '<br>');
};
</script>

<style scoped>
.etl-chat-widget {
  width: 100%;
  max-width: 600px;
  height: 700px;
  border: 1px solid #e0e0e0;
  border-radius: 12px;
  display: flex;
  flex-direction: column;
  background-color: #fff;
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.1);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
}

.chat-header {
  padding: 16px 20px;
  border-bottom: 1px solid #e0e0e0;
  background-color: #f8f9fa;
  border-radius: 12px 12px 0 0;
}

.title {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
  color: #1a1a1a;
}

.subtitle {
  margin: 4px 0 0 0;
  font-size: 13px;
  color: #666;
}

.session-info {
  margin-top: 8px;
  display: flex;
  align-items: center;
  gap: 8px;
}

.session-id {
  font-size: 11px;
  color: #999;
}

.phase-badge {
  padding: 4px 12px;
  border-radius: 12px;
  font-size: 11px;
  font-weight: 500;
  text-transform: uppercase;
}

.status-bar {
  padding: 8px 16px;
  font-size: 12px;
  text-align: center;
}

.status-bar.success {
  background-color: #d4edda;
  color: #155724;
}

.messages-container {
  flex: 1;
  overflow-y: auto;
  padding: 20px;
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.message {
  max-width: 85%;
  padding: 12px 16px;
  border-radius: 12px;
  font-size: 14px;
  line-height: 1.6;
  word-wrap: break-word;
}

.message.user {
  align-self: flex-end;
  background-color: #007bff;
  color: #fff;
  border-bottom-right-radius: 4px;
}

.message.bot {
  align-self: flex-start;
  background-color: #f1f3f4;
  color: #1a1a1a;
  border-bottom-left-radius: 4px;
}

.message.error {
  background-color: #f8d7da;
  color: #721c24;
}

.pipeline-badge {
  display: inline-block;
  padding: 4px 8px;
  background-color: #28a745;
  color: #fff;
  border-radius: 4px;
  font-size: 12px;
  margin-top: 8px;
}

.input-container {
  padding: 16px 20px;
  border-top: 1px solid #e0e0e0;
  display: flex;
  gap: 12px;
}

.message-input {
  flex: 1;
  padding: 12px 16px;
  border: 1px solid #ddd;
  border-radius: 24px;
  font-size: 14px;
  outline: none;
  transition: border-color 0.2s;
}

.message-input:focus {
  border-color: #007bff;
}

.send-button {
  padding: 12px 24px;
  background-color: #007bff;
  color: #fff;
  border: none;
  border-radius: 24px;
  font-size: 14px;
  font-weight: 500;
  cursor: pointer;
  transition: background-color 0.2s;
}

.send-button:hover:not(:disabled) {
  background-color: #0056b3;
}

.send-button:disabled {
  background-color: #ccc;
  cursor: not-allowed;
}
</style>
